Traceback (most recent call last):
  File "/nfs/hpc/share/isonc/oregon_wildlife_identification/model_benchmarking/batch_animal_count_training.py", line 355, in <module>
    train_and_validate(num_epochs, resnet152, "ResNet152", training_data_set, validation_data_set, batch_training_data_set, batch_validation_data_set, device, saving_dir, batch_size, False)
  File "/nfs/hpc/share/isonc/oregon_wildlife_identification/model_benchmarking/batch_animal_count_training.py", line 278, in train_and_validate
    val_mse, val_mae, val_acc = validation(model, validation_data_set, mse, mae, device, batch_size)
  File "/nfs/hpc/share/isonc/oregon_wildlife_identification/model_benchmarking/batch_animal_count_training.py", line 162, in validation
    output = model(data).flatten()
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torchvision/models/resnet.py", line 275, in _forward_impl
    x = self.layer3(x)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torchvision/models/resnet.py", line 150, in forward
    out = self.conv2(out)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/nfs/stak/users/isonc/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 29.68 GiB already allocated; 5.00 MiB free; 30.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

